[pytest]
# Define qué archivos, clases y funciones va a reconocer Pytest como tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Opciones por defecto al ejecutar pytest
addopts = -v --html=reports/reporte.html --self-contained-html